<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JayCe Leonard">
<meta name="dcterms.date" content="2025-03-22">

<title>Steam March 2025, Analyzing Discoverability in the Steam Marketplace</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="final_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_files/libs/quarto-html/quarto.js"></script>
<script src="final_files/libs/quarto-html/popper.min.js"></script>
<script src="final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_files/libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_files/libs/bootstrap/bootstrap-e57b7b0bc837211718f340ae508b3b77.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#steam-games-dataset-march-2025" id="toc-steam-games-dataset-march-2025" class="nav-link" data-scroll-target="#steam-games-dataset-march-2025">Steam Games Dataset March 2025</a>
  <ul class="collapse">
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview">Dataset Overview</a></li>
  <li><a href="#dataset-columns" id="toc-dataset-columns" class="nav-link" data-scroll-target="#dataset-columns">Dataset Columns</a></li>
  <li><a href="#key-metrics-distribution" id="toc-key-metrics-distribution" class="nav-link" data-scroll-target="#key-metrics-distribution">Key Metrics Distribution</a>
  <ul class="collapse">
  <li><a href="#pricing-and-commercial-attributes" id="toc-pricing-and-commercial-attributes" class="nav-link" data-scroll-target="#pricing-and-commercial-attributes">Pricing and Commercial Attributes</a></li>
  <li><a href="#player-engagement" id="toc-player-engagement" class="nav-link" data-scroll-target="#player-engagement">Player Engagement</a></li>
  <li><a href="#game-features" id="toc-game-features" class="nav-link" data-scroll-target="#game-features">Game Features</a></li>
  <li><a href="#playtime-metrics" id="toc-playtime-metrics" class="nav-link" data-scroll-target="#playtime-metrics">Playtime Metrics</a></li>
  </ul></li>
  <li><a href="#dataset-methodology" id="toc-dataset-methodology" class="nav-link" data-scroll-target="#dataset-methodology">Dataset Methodology</a></li>
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">Data Acquisition</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  <li><a href="#steam-metrics-background" id="toc-steam-metrics-background" class="nav-link" data-scroll-target="#steam-metrics-background">Steam Metrics Background</a>
  <ul class="collapse">
  <li><a href="#concurrent-players" id="toc-concurrent-players" class="nav-link" data-scroll-target="#concurrent-players">Concurrent Players</a></li>
  <li><a href="#review-percentages" id="toc-review-percentages" class="nav-link" data-scroll-target="#review-percentages">Review Percentages</a></li>
  <li><a href="#metacritic-integration" id="toc-metacritic-integration" class="nav-link" data-scroll-target="#metacritic-integration">Metacritic Integration</a></li>
  </ul></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a>
  <ul class="collapse">
  <li><a href="#game-volume-prediction" id="toc-game-volume-prediction" class="nav-link" data-scroll-target="#game-volume-prediction"><strong>Game Volume Prediction</strong>:</a></li>
  <li><a href="#are-older-games-blocking-people-from-trying-new-games" id="toc-are-older-games-blocking-people-from-trying-new-games" class="nav-link" data-scroll-target="#are-older-games-blocking-people-from-trying-new-games"><strong>Are Older Games Blocking People from Trying New Games?</strong>:</a></li>
  <li><a href="#what-factors-are-most-impactful-for-getting-new-players-to-join" id="toc-what-factors-are-most-impactful-for-getting-new-players-to-join" class="nav-link" data-scroll-target="#what-factors-are-most-impactful-for-getting-new-players-to-join"><strong>What “Factors” Are Most Impactful for Getting New Players to Join?</strong>:</a></li>
  <li><a href="#can-i-predict-larger-competitors-through-indirect-predictors" id="toc-can-i-predict-larger-competitors-through-indirect-predictors" class="nav-link" data-scroll-target="#can-i-predict-larger-competitors-through-indirect-predictors"><strong>Can I Predict Larger Competitors Through Indirect Predictors?</strong>:</a></li>
  </ul></li>
  <li><a href="#liniar-regression---game-volume-prediction" id="toc-liniar-regression---game-volume-prediction" class="nav-link" data-scroll-target="#liniar-regression---game-volume-prediction">Liniar Regression - Game volume prediction</a>
  <ul class="collapse">
  <li><a href="#volume-prediction-2025" id="toc-volume-prediction-2025" class="nav-link" data-scroll-target="#volume-prediction-2025">Volume Prediction 2025</a></li>
  <li><a href="#understanding-steams-game-growth-pattern" id="toc-understanding-steams-game-growth-pattern" class="nav-link" data-scroll-target="#understanding-steams-game-growth-pattern">Understanding Steam’s Game Growth Pattern</a></li>
  </ul></li>
  <li><a href="#are-older-game-blocking-people-from-trying-new-games" id="toc-are-older-game-blocking-people-from-trying-new-games" class="nav-link" data-scroll-target="#are-older-game-blocking-people-from-trying-new-games">Are older Game blocking people from trying new games?</a>
  <ul class="collapse">
  <li><a href="#support-vector-classifier" id="toc-support-vector-classifier" class="nav-link" data-scroll-target="#support-vector-classifier">Support Vector Classifier</a>
  <ul class="collapse">
  <li><a href="#svc-graph-explination" id="toc-svc-graph-explination" class="nav-link" data-scroll-target="#svc-graph-explination">SVC graph explination</a></li>
  <li><a href="#multi-svc" id="toc-multi-svc" class="nav-link" data-scroll-target="#multi-svc">Multi SVC</a></li>
  </ul></li>
  <li><a href="#volume-density-visualizations" id="toc-volume-density-visualizations" class="nav-link" data-scroll-target="#volume-density-visualizations">Volume Density Visualizations</a>
  <ul class="collapse">
  <li><a href="#market-volume-proxy-explanation" id="toc-market-volume-proxy-explanation" class="nav-link" data-scroll-target="#market-volume-proxy-explanation">Market Volume Proxy Explanation</a></li>
  </ul></li>
  <li><a href="#recent-activity-value-analysis" id="toc-recent-activity-value-analysis" class="nav-link" data-scroll-target="#recent-activity-value-analysis">Recent Activity Value Analysis</a></li>
  <li><a href="#volume-density-visualizations-1" id="toc-volume-density-visualizations-1" class="nav-link" data-scroll-target="#volume-density-visualizations-1">Volume Density Visualizations</a></li>
  </ul></li>
  <li><a href="#what-are-factors-are-most-impactiful-for-getting-new-players-to-join" id="toc-what-are-factors-are-most-impactiful-for-getting-new-players-to-join" class="nav-link" data-scroll-target="#what-are-factors-are-most-impactiful-for-getting-new-players-to-join">What are “factors” are most impactiful for getting new players to join?</a>
  <ul class="collapse">
  <li><a href="#pca---discussion" id="toc-pca---discussion" class="nav-link" data-scroll-target="#pca---discussion">PCA - Discussion</a></li>
  </ul></li>
  <li><a href="#market-competitiveness-prediction-through-indirect-predictors" id="toc-market-competitiveness-prediction-through-indirect-predictors" class="nav-link" data-scroll-target="#market-competitiveness-prediction-through-indirect-predictors">Market Competitiveness Prediction Through Indirect Predictors</a>
  <ul class="collapse">
  <li><a href="#rf-experiment" id="toc-rf-experiment" class="nav-link" data-scroll-target="#rf-experiment">RF experiment</a>
  <ul class="collapse">
  <li><a href="#misclassification-heatmap-analysis" id="toc-misclassification-heatmap-analysis" class="nav-link" data-scroll-target="#misclassification-heatmap-analysis">Misclassification Heatmap Analysis</a></li>
  <li><a href="#cross-validation-summary" id="toc-cross-validation-summary" class="nav-link" data-scroll-target="#cross-validation-summary">Cross-Validation Summary</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#impact" id="toc-impact" class="nav-link" data-scroll-target="#impact">Impact</a>
  <ul class="collapse">
  <li><a href="#steam-marketplace-analysis" id="toc-steam-marketplace-analysis" class="nav-link" data-scroll-target="#steam-marketplace-analysis">Steam Marketplace Analysis</a></li>
  <li><a href="#critical-success-factors" id="toc-critical-success-factors" class="nav-link" data-scroll-target="#critical-success-factors">Critical Success Factors</a></li>
  <li><a href="#strategic-implications-for-developers" id="toc-strategic-implications-for-developers" class="nav-link" data-scroll-target="#strategic-implications-for-developers">Strategic Implications for Developers</a></li>
  </ul></li>
  <li><a href="#ai-assistance-disclaimer" id="toc-ai-assistance-disclaimer" class="nav-link" data-scroll-target="#ai-assistance-disclaimer">AI Assistance Disclaimer</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Steam March 2025, Analyzing Discoverability in the Steam Marketplace</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>JayCe Leonard </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 22, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>This study investigates the “invisible games” phenomenon on Steam’s digital marketplace through comprehensive analysis of 89,618 game titles. Our findings challenge common perceptions about marketplace entrenchment by demonstrating that established blockbusters occupy only 0.4% of the catalog while still commanding significant player attention. Random Forest modeling (achieving 0.992 accuracy, 0.863 precision) reveals that recent positive review percentage (0.3560 importance) is substantially more predictive of market competitiveness than any volume-based metric, highlighting player rapport as the critical factor in sustained commercial viability. The temporal analysis identifies a natural decay pattern in game engagement (steepest between 3-5 years post-release), creating opportunities for new entrants despite apparent market saturation. Approximately 37% of earnest commercial attempts fall below critical visibility thresholds, suggesting significant market inefficiencies, while 12.4% of games achieve at least moderate success (10+ recent reviews). Support Vector Machine classification demonstrates that the marketplace remains accessible to quality new entries, with player engagement patterns naturally diminishing for even successful legacy games over time. These findings offer evidence-based insights for developers, suggesting a focus on community engagement rather than competing directly with established titles.</p>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<p>Due to the substantial size of this dataset (89,618 game entries with 46 variables), computational constraints necessitated limitations in the validation methodology. The SVM multi-classifier was trained directly with the test set rather than using extensive cross-validation, which may impact the generalizability of classification boundaries. Additionally, the Random Forest implementation was restricted to 5-fold cross-validation rather than more comprehensive validation approaches that might have provided greater confidence in model performance. I also ended up cutting a significant portion of the genre count analysis because iterations on the modeling and visualizations were consuming too much time. These computational and time-constraint trade-offs were necessary to maintain analytical feasibility while working with such a large and feature-rich dataset, though they should be considered when interpreting the precision of decision boundaries and classification metrics.</p>
</section>
<section id="steam-games-dataset-march-2025" class="level1">
<h1>Steam Games Dataset March 2025</h1>
<section id="dataset-overview" class="level2">
<h2 class="anchored" data-anchor-id="dataset-overview">Dataset Overview</h2>
<p>The analysis utilizes a comprehensive Steam games dataset containing <strong>89,618 unique game entries</strong>, capturing a wide range of metrics related to game performance, player engagement, and market positioning.</p>
</section>
<section id="dataset-columns" class="level2">
<h2 class="anchored" data-anchor-id="dataset-columns">Dataset Columns</h2>
<p>The dataset contains 46 columns covering various aspects of each game:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Column Names</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Game Identification</strong></td>
<td>appid, name, release_date</td>
</tr>
<tr class="even">
<td><strong>Game Details</strong></td>
<td>required_age, price, dlc_count, detailed_description, about_the_game, short_description, header_image, website</td>
</tr>
<tr class="odd">
<td><strong>Platform Support</strong></td>
<td>windows, mac, linux</td>
</tr>
<tr class="even">
<td><strong>Support Information</strong></td>
<td>support_url, support_email</td>
</tr>
<tr class="odd">
<td><strong>Reviews &amp; Ratings</strong></td>
<td>reviews, metacritic_score, metacritic_url, user_score, score_rank, positive, negative, pct_pos_total, num_reviews_total, pct_pos_recent, num_reviews_recent</td>
</tr>
<tr class="even">
<td><strong>Game Features</strong></td>
<td>achievements, supported_languages, full_audio_languages, packages, categories, genres, screenshots, movies, tags</td>
</tr>
<tr class="odd">
<td><strong>Developer Information</strong></td>
<td>developers, publishers, notes</td>
</tr>
<tr class="even">
<td><strong>Player Engagement</strong></td>
<td>recommendations, estimated_owners, average_playtime_forever, average_playtime_2weeks, median_playtime_forever, median_playtime_2weeks, peak_ccu</td>
</tr>
<tr class="odd">
<td><strong>Commercial Data</strong></td>
<td>discount</td>
</tr>
</tbody>
</table>
</section>
<section id="key-metrics-distribution" class="level2">
<h2 class="anchored" data-anchor-id="key-metrics-distribution">Key Metrics Distribution</h2>
<section id="pricing-and-commercial-attributes" class="level3">
<h3 class="anchored" data-anchor-id="pricing-and-commercial-attributes">Pricing and Commercial Attributes</h3>
<ul>
<li><strong>Average price</strong>: $7.31 (SD = $13.33)</li>
<li><strong>Price range</strong>: $0.00 to $999.98</li>
<li><strong>DLC content</strong>: Average of 0.60 DLCs per game</li>
<li><strong>Average discount</strong>: 4.56% (with maximum discounts reaching 100%)</li>
</ul>
</section>
<section id="player-engagement" class="level3">
<h3 class="anchored" data-anchor-id="player-engagement">Player Engagement</h3>
<ul>
<li><strong>Recommendations</strong>: Mean of 1,009 recommendations per game</li>
<li><strong>Reviews</strong>: Average of 1,315 total reviews per title</li>
<li><strong>Recent reviews</strong>: Mean of 15.58 reviews in recent period</li>
<li><strong>Positive sentiment</strong>: Average of 45.35% positive rating across all games</li>
<li><strong>Peak concurrent users</strong>: Mean of 98.34 players (maximum of 1,212,356)</li>
</ul>
</section>
<section id="game-features" class="level3">
<h3 class="anchored" data-anchor-id="game-features">Game Features</h3>
<ul>
<li><strong>Achievements</strong>: Average of 20.55 achievements per game (maximum of 9,821)</li>
<li><strong>Metacritic score</strong>: Mean score of 2.90 (maximum of 97)</li>
<li><strong>Age requirements</strong>: Mean required age of 0.18 years</li>
</ul>
</section>
<section id="playtime-metrics" class="level3">
<h3 class="anchored" data-anchor-id="playtime-metrics">Playtime Metrics</h3>
<ul>
<li><strong>Average playtime (forever)</strong>: 114.91 hours</li>
<li><strong>Average playtime (2 weeks)</strong>: 5.03 hours</li>
<li><strong>Median playtime (forever)</strong>: 114.76 hours</li>
<li><strong>Median playtime (2 weeks)</strong>: 5.30 hours</li>
</ul>
</section>
</section>
<section id="dataset-methodology" class="level2">
<h2 class="anchored" data-anchor-id="dataset-methodology">Dataset Methodology</h2>
<p>This multi-source approach ensures a robust and comprehensive representation of the digital gaming marketplace, capturing nuanced details across different data collection mechanisms. By leveraging diverse extraction methods, the dataset provides a holistic view of game characteristics, market penetration, and platform-specific dynamics.</p>
<p>Two distinct versions of the dataset are provided to support varied research requirements. The raw parsed dataset (<code>games_march2025_full.csv</code>) contains the complete, unprocessed scrape of Steam store data, preserving all game entries including potential duplicates and playtest versions. This version enables exploratory research and supports comprehensive data examination.</p>
<p>Complementing the raw dataset, the cleaned version (<code>games_march2025_cleaned.csv</code>) offers a refined research instrument. Through systematic processing, duplicate entries are removed, playtest versions are filtered out, and the data is optimized for rigorous statistical analysis. This version provides researchers with a streamlined, high-quality data resource.</p>
</section>
<section id="data-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition">Data Acquisition</h2>
<p>Researchers can efficiently retrieve the dataset utilizing the Kaggle Hub Python library. The acquisition process is straightforward, allowing immediate access to the most current version of the Steam games dataset.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> kagglehub</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Download latest version</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> kagglehub.dataset_download(<span class="st">"artermiloff/steam-games-dataset"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Path to dataset files:"</span>, path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The dataset is contemporaneous as of March 2025, providing researchers with a precise temporal snapshot of the Steam game marketplace ecosystem. This current iteration captures the dynamic landscape of digital game distribution at a specific point in time, enabling meaningful comparative and trend analysis.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>FronkonGames. (2025). Steam Games Scraper [Computer software]. GitHub. https://github.com/FronkonGames/Steam-Games-Scraper</li>
</ul>
</section>
</section>
<section id="steam-metrics-background" class="level1">
<h1>Steam Metrics Background</h1>
<section id="concurrent-players" class="level2">
<h2 class="anchored" data-anchor-id="concurrent-players">Concurrent Players</h2>
<p>Concurrent players measures users simultaneously playing a game. High counts (10,000+) indicate strong engagement, while 1,000+ typically ensures commercial viability. This metric fluctuates with updates, streaming popularity, and seasonal events.</p>
</section>
<section id="review-percentages" class="level2">
<h2 class="anchored" data-anchor-id="review-percentages">Review Percentages</h2>
<p>Steam separates ratings into “Recent” (last 30 days) and “Overall” (all-time) percentages, showing the proportion of positive reviews. Recent percentages respond quickly to changes, while Overall provides historical context. Significant disparities between these metrics typically indicate major changes in quality or business decisions.</p>
</section>
<section id="metacritic-integration" class="level2">
<h2 class="anchored" data-anchor-id="metacritic-integration">Metacritic Integration</h2>
<p>Steam displays Metacritic scores (0-100) for professionally reviewed games. Research suggests scores above 75 correlate with better commercial performance, while scores below 50 can significantly impact sales potential regardless of marketing budget. Unlike user reviews, these scores remain static after initial release unless a remaster is released.</p>
</section>
</section>
<section id="research-questions" class="level1">
<h1>Research Questions</h1>
<p>This research investigates several critical aspects of the Steam gaming marketplace ecosystem through data analysis and modeling techniques to provide actionable insights for game developers, platform operators, and industry stakeholders.</p>
<section id="game-volume-prediction" class="level2">
<h2 class="anchored" data-anchor-id="game-volume-prediction"><strong>Game Volume Prediction</strong>:</h2>
<p>How has the Steam marketplace grown over time, and what mathematical models best describe this growth pattern? Can we accurately predict future marketplace volume based on historical trends? This analysis examines exponential, linear, quadratic, and cubic models to determine which best characterizes the platform’s expansion trajectory and provides reliable forecasting.</p>
</section>
<section id="are-older-games-blocking-people-from-trying-new-games" class="level2">
<h2 class="anchored" data-anchor-id="are-older-games-blocking-people-from-trying-new-games"><strong>Are Older Games Blocking People from Trying New Games?</strong>:</h2>
<p>To what extent do established legacy titles create barriers to entry for new releases? This investigation challenges the common perception that the marketplace is “entrenched” by quantifying the proportional influence of blockbuster games and analyzing temporal engagement patterns to determine if market saturation truly prevents new titles from finding audiences.</p>
</section>
<section id="what-factors-are-most-impactful-for-getting-new-players-to-join" class="level2">
<h2 class="anchored" data-anchor-id="what-factors-are-most-impactful-for-getting-new-players-to-join"><strong>What “Factors” Are Most Impactful for Getting New Players to Join?</strong>:</h2>
<p>Which game attributes and performance metrics most strongly correlate with commercial success and player engagement? This analysis evaluates user review patterns, pricing strategies, and content characteristics to identify the critical drivers of player adoption and community growth, with particular focus on the relative importance of quality versus marketing volume.</p>
</section>
<section id="can-i-predict-larger-competitors-through-indirect-predictors" class="level2">
<h2 class="anchored" data-anchor-id="can-i-predict-larger-competitors-through-indirect-predictors"><strong>Can I Predict Larger Competitors Through Indirect Predictors?</strong>:</h2>
<p>Is it possible to develop reliable models that identify market competitors based on indirect engagement metrics rather than direct sales figures? This exploratory research implements Support Vector Machine (SVM) classification and Random Forest modeling to determine if publicly available data can effectively predict commercial viability and competitive position within the marketplace.</p>
<p>Through these interconnected research questions, the study aims to provide evidence-based insights into the complex dynamics of digital game distribution and help developers navigate an increasingly challenging competitive landscape.</p>
</section>
</section>
<section id="liniar-regression---game-volume-prediction" class="level1">
<h1>Liniar Regression - Game volume prediction</h1>
<div id="cell-6" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> cs670.CsvManager.get_steam2025_df()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>cs670.qh.lm_gamecount(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/home/jpleona/jpleona_c/steamapi-project/steam-api-project/cs670/quarto_helpers.py:88: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  }).set_index('date').resample('M').count().reset_index()</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-3-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Performance Summary:
Linear Model:      R² = 0.6688, MSE = 185571061.43
Quadratic Model:   R² = 0.9481, MSE = 29064869.04
Cubic Model:       R² = 0.9969, MSE = 1716218.26
Exponential Model: R² = 0.3891, MSE = 342256302.96

Linear Model Coefficients:
Intercept: -16827.22
Slope: 5.7714 games per day
Estimated annual growth rate: 2106.57 games per year

Quadratic Model Coefficients:
Intercept: 11802.90
X coefficient: -11.202438
X² coefficient: 0.00168476</code></pre>
</div>
</div>
<section id="volume-prediction-2025" class="level3">
<h3 class="anchored" data-anchor-id="volume-prediction-2025">Volume Prediction 2025</h3>
<div id="cell-8" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> cs670.qh.project_steam_games(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    df, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    target_date<span class="op">=</span>datetime(<span class="dv">2026</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    polynomial_degree<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    fig_path<span class="op">=</span><span class="st">'steam_games_projection_2026.png'</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Polynomial Model (degree 3) Coefficients:
Intercept: -3389.1360
X^1 coefficient: 6.744783018945
X^2 coefficient: -0.002708040567
X^3 coefficient: 0.000000287413

Prediction for January 01, 2026:
Predicted total number of games: 97,679
Current number of games (as of today): 85,651
Last recorded number in dataset (as of 2025-03-31): 89,618
Projected increase from today to January 01, 2026: 12,028 games</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-4-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="understanding-steams-game-growth-pattern" class="level2">
<h2 class="anchored" data-anchor-id="understanding-steams-game-growth-pattern">Understanding Steam’s Game Growth Pattern</h2>
<p>The extremely high R² value (0.9969) for the cubic model reveals an important insight about Steam’s platform expansion. This remarkably close fit suggests we’ve uncovered the underlying algorithm that determines how many games Steam is willing to host each year. Rather than representing organic, unpredictable market growth, the cubic pattern indicates a deliberate and systematic approach to platform scaling.</p>
<p>The cubic function (with its third-degree polynomial) appears to be the mathematical formula driving Steam’s internal capacity planning. This explains why the R² value approaches perfect correlation - we’re not simply modeling market behavior, but reverse-engineering Steam’s own expansion algorithm. The exceptionally low MSE value (1,716,218.26) further confirms that this cubic function represents the actual decision-making process behind Steam’s game catalog growth.</p>
<p>This discovery has significant implications for developers and publishers, as it suggests Steam’s growth follows a predictable mathematical pattern rather than responding dynamically to market forces or quality considerations.</p>
</section>
</section>
<section id="are-older-game-blocking-people-from-trying-new-games" class="level1">
<h1>Are older Game blocking people from trying new games?</h1>
<div id="cell-11" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> cs670.qh.plot_game_reviews_over_time(df, save_path<span class="op">=</span><span class="st">'steam_games_review_date_scatter.png'</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-12" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>cluster_fig, stats_fig, cluster_data <span class="op">=</span> cs670.qh.visualize_game_clusters(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    df, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    k<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    save_path<span class="op">=</span><span class="st">'steam_games_kmeans_clusters.png'</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="support-vector-classifier" class="level2">
<h2 class="anchored" data-anchor-id="support-vector-classifier">Support Vector Classifier</h2>
<ol type="1">
<li>Is The Market as “Entrenched” as People Claim?</li>
</ol>
<p>With the following graphs I am attempting to describe if people are biased enough toward newer games to support new releases.</p>
<p>Looking at the Steam games distribution, <strong>older games with fewer reviews tend to fade into obscurity</strong> while <strong>newer releases consistently attract player attention regardless of size</strong>. Although technically competing with established giants, <strong>the market remains receptive to new entries</strong> as shown by the varied review counts across recent years, demonstrating that <strong>players still give new games a fair chance</strong> despite the crowded marketplace.</p>
<div id="cell-14" class="cell" data-execution_count="27">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> cs670.qh.visualize_steam_game_metrics2(df, save_path<span class="op">=</span><span class="st">'steam_game_analysis.png'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-15" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># df = pd.read_csv('path/to/steam_games_data.csv')</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> cs670.qh.visualize_steam_game_metrics_with_boundary(df, save_path<span class="op">=</span><span class="st">'steam_game_analysis_boundary.png'</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="svc-graph-explination" class="level3">
<h3 class="anchored" data-anchor-id="svc-graph-explination">SVC graph explination</h3>
<p>Looking at the Steam games distribution, older games with fewer reviews tend to fade into obscurity while newer releases consistently attract player attention regardless of size. Although technically competing with established giants, the market remains receptive to new entries as shown by the varied review counts across recent years, demonstrating that players still give new games a fair chance despite the crowded marketplace.</p>
<div id="cell-17" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># df = pd.read_csv('path/to/steam_games_data.csv')</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> cs670.qh.visualize_steam_games_with_svm_boundaries(df, save_path<span class="op">=</span><span class="st">'steam_review_svm_boundaries.png'</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>10+ recent reviews: 6621 games (12.4%)
100+ recent reviews: 1574 games (3.0%)
1000+ recent reviews: 226 games (0.4%)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multi-svc" class="level3">
<h3 class="anchored" data-anchor-id="multi-svc">Multi SVC</h3>
<p>This chart uses SVM decision boundaries to illustrate how recent review activity varies across Steam games over time. The purple boundary (1000+ recent reviews) demonstrates that mega hits maintain significant player engagement years after release, with some titles from as far back as 2012 still generating substantial activity. The red and green boundaries (100+ and 10+ recent reviews) show more modest but still notable engagement patterns. The visualization confirms that established blockbusters dominate player attention long-term, creating persistent competitive pressure from legacy titles. However, the substantial presence of games within the middle boundaries indicates moderate success remains achievable, suggesting the market, while challenging, isn’t completely closed to newer entrants despite the enduring influence of major hits.</p>
<div id="cell-19" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>experiment <span class="op">=</span> cs670.qh.run_svm_cross_validation_experiment(df, save_path<span class="op">=</span><span class="st">'svm_experiment_results'</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Running cross-validation for 10+ recent reviews threshold</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Class balance: 6621 games with 10+ recent reviews (12.4%)</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting 5 folds for each of 40 candidates, totalling 200 fits</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Best parameters: {'C': 100, 'class_weight': None, 'gamma': 1}</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Best cross-validation F1 score: 0.7833</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Running cross-validation for 10+ recent reviews threshold
Class balance: 6621 games with 10+ recent reviews (12.4%)
Fitting 5 folds for each of 40 candidates, totalling 200 fits
Best parameters: {'C': 100, 'class_weight': None, 'gamma': 1}
Best cross-validation F1 score: 0.7833</code></pre>
</div>
</div>
</section>
</section>
<section id="volume-density-visualizations" class="level2">
<h2 class="anchored" data-anchor-id="volume-density-visualizations">Volume Density Visualizations</h2>
<section id="market-volume-proxy-explanation" class="level3">
<h3 class="anchored" data-anchor-id="market-volume-proxy-explanation">Market Volume Proxy Explanation</h3>
<p>The “Recent Activity Value” metric (Recent Reviews × Price) serves as a proxy for a game’s current market performance. This calculation estimates commercial activity by multiplying the number of recent reviews by the game’s price, providing an approximate revenue indicator. Since Steam reviews typically represent a small percentage of actual purchases (estimated at 1-5%), this value offers a relative measure of current commercial performance without requiring access to private sales data. This proxy helps identify which games maintain active communities and revenue generation long after release versus those that experience rapid decline in player engagement.</p>
<div id="cell-21" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> cs670.qh.visualize_recent_activity_value(df, save_path<span class="op">=</span><span class="st">'market_value_visualization.png'</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>/home/jpleona/jpleona_c/steamapi-project/steam-api-project/.venv/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-11-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="recent-activity-value-analysis" class="level2">
<h2 class="anchored" data-anchor-id="recent-activity-value-analysis">Recent Activity Value Analysis</h2>
<p>This scatter plot displays Steam games by release date (y-axis) and recent activity value (x-axis), with dot size indicating review count and color showing total review count on a logarithmic scale.</p>
<p>The vast majority of Steam games (82,931 or 92.5%) have no recent reviews. Among games with activity, most (5,097 games) have only 10-99 recent reviews, while just 233 games (0.3%) exceed 1000+ recent reviews. The highest activity value recorded is $2,349,028.</p>
<p>The visualization reveals a clear boundary line forming the right edge of the distribution, suggesting a natural limit to how much value a game can generate at each review tier. Games from 2014-present dominate the visual space, with older successful titles appearing as isolated points. Higher-value games (right side) typically maintain their position over time, showing stability in the highest earning segments.</p>
<div id="cell-23" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> cs670.qh.visualize_market_volume_kde(df, save_path<span class="op">=</span><span class="st">'market_volume_kde.png'</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="volume-density-visualizations-1" class="level2">
<h2 class="anchored" data-anchor-id="volume-density-visualizations-1">Volume Density Visualizations</h2>
<p>This KDE plot shows Steam game distribution by release date and market volume (recent reviews × price). The red hotspot reveals most games cluster in recent years with low market volumes. Steam’s growth exploded after 2012, with dramatic density increases post-2016. With 5,258 active games versus 84,360 inactive ones, the marketplace shows extreme inequality - the median game earns just $479.76 in recent market volume, while the top performer reaches $2.3+ million. A striking 90% of games generate less than $6,568.65, demonstrating digital distribution’s winner-take-all reality.</p>
</section>
</section>
<section id="what-are-factors-are-most-impactiful-for-getting-new-players-to-join" class="level1">
<h1>What are “factors” are most impactiful for getting new players to join?</h1>
<div id="cell-26" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>analysis <span class="op">=</span> cs670.qh.analyze_steam_market_competitors(df)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Found </span><span class="sc">{</span>analysis[<span class="st">'stats'</span>][<span class="st">'competitors'</span>]<span class="sc">}</span><span class="ss"> market competitors (</span><span class="sc">{</span>analysis[<span class="st">'stats'</span>][<span class="st">'competitor_pct'</span>]<span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Top features correlated with success:"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(analysis[<span class="st">'correlations'</span>].head(<span class="dv">5</span>))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Best price points</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Most successful price points:"</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(analysis[<span class="st">'recommendations'</span>][<span class="st">'price_points'</span>][[<span class="st">'Price_Band'</span>, <span class="st">'Success_Rate'</span>]].head(<span class="dv">3</span>))</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Show cluster visualization</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">'figures'</span> <span class="kw">in</span> analysis <span class="kw">and</span> <span class="st">'clusters'</span> <span class="kw">in</span> analysis[<span class="st">'figures'</span>]:</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    analysis[<span class="st">'figures'</span>][<span class="st">'clusters'</span>].show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Found 6322 market competitors (7.05%)

Top features correlated with success:
             Feature  Correlation
13    pct_pos_recent     0.955093
4   metacritic_score     0.290756
12     pct_pos_total     0.261600
24      movies_count     0.183597
1       required_age     0.174430

Most successful price points:
      Price_Band  Success_Rate
8  $50.00-$59.99     55.514706
7  $40.00-$49.99     39.423077
6  $30.00-$39.99     39.420655</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-13-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="pca---discussion" class="level2">
<h2 class="anchored" data-anchor-id="pca---discussion">PCA - Discussion</h2>
<p>The PCA implementation reveals critical insights about feature effectiveness across different competitor thresholds. For the initial 10+ recent reviews threshold, <strong>simply having any reviews at all proved to be a dominant predictor</strong>, as games rarely fall into the 1-9 reviews range. This makes competitor detection at this threshold relatively straightforward. However, when shifting to the more challenging 100+ reviews threshold, <strong>the prediction task becomes substantially more difficult and less trivial</strong>. The PCA confirms that features highly effective for the 10+ threshold lose much of their predictive power at higher thresholds, requiring more sophisticated feature combinations. This explains the selection of these particular features for the model, as they offered the best performance for discriminating between truly competitive games (100+ recent reviews) rather than simply detecting minimal market presence. The PCA dimensionality reduction clearly illustrates this complexity shift between threshold levels.</p>
</section>
</section>
<section id="market-competitiveness-prediction-through-indirect-predictors" class="level1">
<h1>Market Competitiveness Prediction Through Indirect Predictors</h1>
<p>The data demonstrates the feasibility of predicting market competitors through indirect metrics using Random Forest modeling. Defining market competitors as games with 100+ recent reviews (representing only 1.8% of the total marketplace), the analysis achieved impressive performance metrics (accuracy: 0.992, precision: 0.863, recall: 0.658, F1 score: 0.747) through 5-fold cross-validation. The model effectively identifies commercially successful titles despite the extreme class imbalance in the dataset. Feature importance analysis reveals that recent positive review percentage (0.3560) is the dominant predictor of competitive status, significantly outweighing traditional volume metrics. Other influential factors include peak concurrent users (0.2017), positive review count (0.1498), negative review count (0.1187), and total positive review percentage (0.0533). This suggests that player sentiment and engagement quality are substantially more predictive of marketplace success than raw engagement volume, challenging conventional metrics focused primarily on total sales or downloads. The model’s strength in precision over recall indicates it’s more conservative in predicting competitive status, minimizing false positives while accepting some false negatives—a valuable characteristic for developers seeking to realistically assess their competitive positioning.</p>
<section id="rf-experiment" class="level2">
<h2 class="anchored" data-anchor-id="rf-experiment">RF experiment</h2>
<div id="cell-28" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cs670</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> importlib</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>importlib.<span class="bu">reload</span>(cs670.qh)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>analysis <span class="op">=</span> cs670.qh.analyze_steam_competitors_rf(df)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># # Access the misclassification analysis</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(analysis[<span class="st">'summary'</span>])</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># # View figures</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>analysis[<span class="st">'figures'</span>][<span class="st">'confusion_matrix'</span>].show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Running Random Forest analysis with 5-fold cross-validation...
Market competitor definition: 100+ recent reviews
Skipping confidence ellipses due to error: Array must not contain infs or NaNs
Random Forest Model Performance for 100+ Recent Reviews:
-------------------------------
Data: 89,618 games, 1,590 competitors (1.8%)
Accuracy: 0.992
Precision: 0.863
Recall: 0.658
F1 Score: 0.747

Misclassification Analysis:
--------------------------
False Positives: 166 games (0.2% of all games)
False Negatives: 543 games (0.6% of all games)
Low Confidence True Positives: 112 games (7.0% of all competitors)

Key Insights:
------------
False Positives (predicted as competitors but aren't):
  • Avg total reviews: 18943.5, Avg recent reviews: 67.6
  • peak_ccu: 85.7% lower than actual competitors
  • positive: 66.2% lower than actual competitors
  • negative: 53.1% lower than actual competitors

False Negatives (actual competitors predicted as non-competitors):
  • Avg total reviews: 13294.9, Avg recent reviews: 428.8
  • peak_ccu: 95.1% lower than typical competitors
  • positive: 91.2% lower than typical competitors
  • negative: 89.2% lower than typical competitors

Low Confidence True Positives (correct but uncertain predictions):
  • Avg total reviews: 17886.8, Avg recent reviews: 256.9
  • peak_ccu: 82.0% lower than typical competitors
  • negative: 64.6% lower than typical competitors
  • positive: 64.4% lower than typical competitors

Top 5 features for predicting market competitors:
  1. pct_pos_recent: 0.3560
  2. peak_ccu: 0.2017
  3. positive: 0.1498
  4. negative: 0.1187
  5. pct_pos_total: 0.0533

Random Forest Model Performance for 100+ Recent Reviews:
-------------------------------
Data: 89,618 games, 1,590 competitors (1.8%)
Accuracy: 0.992
Precision: 0.863
Recall: 0.658
F1 Score: 0.747

Misclassification Analysis:
--------------------------
False Positives: 166 games (0.2% of all games)
False Negatives: 543 games (0.6% of all games)
Low Confidence True Positives: 112 games (7.0% of all competitors)

Key Insights:
------------
False Positives (predicted as competitors but aren't):
  • Avg total reviews: 18943.5, Avg recent reviews: 67.6
  • peak_ccu: 85.7% lower than actual competitors
  • positive: 66.2% lower than actual competitors
  • negative: 53.1% lower than actual competitors

False Negatives (actual competitors predicted as non-competitors):
  • Avg total reviews: 13294.9, Avg recent reviews: 428.8
  • peak_ccu: 95.1% lower than typical competitors
  • positive: 91.2% lower than typical competitors
  • negative: 89.2% lower than typical competitors

Low Confidence True Positives (correct but uncertain predictions):
  • Avg total reviews: 17886.8, Avg recent reviews: 256.9
  • peak_ccu: 82.0% lower than typical competitors
  • negative: 64.6% lower than typical competitors
  • positive: 64.4% lower than typical competitors

Top 5 features for predicting market competitors:
  1. pct_pos_recent: 0.3560
  2. peak_ccu: 0.2017
  3. positive: 0.1498
  4. negative: 0.1187
  5. pct_pos_total: 0.0533
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-14-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-14-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="misclassification-heatmap-analysis" class="level3">
<h3 class="anchored" data-anchor-id="misclassification-heatmap-analysis">Misclassification Heatmap Analysis</h3>
<p>The misclassification heatmap exposes the model’s key performance characteristics in predicting market competitors. <strong>The model excels at correctly identifying smaller games that aren’t competitors</strong>, effectively filtering out titles with minimal market presence. However, <strong>it significantly underperforms when evaluating older games with substantial review counts</strong>. This failure manifests as a cluster of false negatives—games that are actually market competitors but predicted as non-competitors. The visualization clearly demonstrates that while total review count and release date work well for newer titles, <strong>these features alone cannot accurately determine whether an established game maintains current commercial viability</strong>. The model essentially fails to distinguish between “has-been” titles and those that continue generating significant revenue years after release. To improve prediction accuracy, features that better capture recent engagement patterns and current market momentum beyond simple review tallies are needed.</p>
</section>
<section id="cross-validation-summary" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation-summary">Cross-Validation Summary</h3>
<p>The cross-validation implementation used stratified k-fold validation to address class imbalance and provide reliable performance metrics. <strong>Precision consistently exceeded recall</strong>, indicating the Random Forest classifier is more conservative in labeling games as competitors. The code identified <strong>systematic misclassification patterns</strong> that persisted across validation folds, particularly with older titles having high total reviews but lower recent engagement. These consistent errors across folds suggest limitations in the feature set rather than algorithmic problems. The validation process quantified both the model’s strengths in filtering small games and its weaknesses in evaluating established titles.</p>
</section>
</section>
</section>
<section id="impact" class="level1">
<h1>Impact</h1>
<section id="steam-marketplace-analysis" class="level2">
<h2 class="anchored" data-anchor-id="steam-marketplace-analysis">Steam Marketplace Analysis</h2>
<p>While data confirms that mega-hits maintain remarkable staying power, <strong>the market reality is more complex than simple entrenchment</strong>. The SVM boundary visualization demonstrates that <strong>established blockbusters occupy a persistent but proportionally small segment of the overall marketplace</strong>. These legacy titles comprise <strong>less than 0.4% of all games</strong> while commanding substantial player attention, creating an asymmetric competitive environment.</p>
<p><strong>The temporal analysis reveals a natural decay pattern even among successful titles</strong>. Games experience a gradual erosion of engagement over time, with <strong>the steepest decline typically occurring between 3-5 years post-release</strong>. This decay creates continual opportunities for new entrants despite the apparent entrenchment of major hits. The substantial presence of moderately successful games within the middle boundaries (10+ and 100+ recent reviews) indicates that <strong>meaningful commercial success remains achievable for newer titles</strong>.</p>
</section>
<section id="critical-success-factors" class="level2">
<h2 class="anchored" data-anchor-id="critical-success-factors">Critical Success Factors</h2>
<p>The most significant finding concerns the primary driver of commercial longevity. The feature importance analysis identified <strong>recent positive review percentage (0.3560) as significantly more predictive of market competitiveness than any volume-based metric</strong>. This suggests that <strong>player rapport—the meaningful connection between developers and their audience—represents the critical factor in sustained commercial viability</strong>. Even massive legacy titles eventually fade without maintaining this player relationship.</p>
</section>
<section id="strategic-implications-for-developers" class="level2">
<h2 class="anchored" data-anchor-id="strategic-implications-for-developers">Strategic Implications for Developers</h2>
<p>For developers concerned about market saturation, the research suggests <strong>a strategic focus on quality and player engagement rather than attempting to compete directly with established titles</strong>. The data demonstrates that <strong>players continually seek and support new experiences</strong> despite having access to successful legacy content. The <strong>12.4% of games achieving at least moderate success</strong> (10+ recent reviews) indicates substantial market receptivity to new offerings that resonate with player expectations.</p>
<p>This evolving ecosystem with natural competitive decay represents a more accessible marketplace than commonly perceived. While competition from established titles creates genuine challenges, <strong>the data conclusively shows that quality new entries continue finding viable audiences</strong>, and even the most successful legacy games eventually yield market space as their player engagement naturally diminishes over time.</p>
</section>
</section>
<section id="ai-assistance-disclaimer" class="level1">
<h1>AI Assistance Disclaimer</h1>
<p>I have dyslexia and use AI to assist with proofreading and structuring my written work. While I personally created all the model training code and analysis, I used AI prompting to iterate on visualization designs and to help format the text for clarity. This collaborative approach helps me communicate my research more effectively while maintaining the integrity of my original analysis and findings.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>